#!/bin/sh


#PBS -l nodes=1:ppn=8
#PBS -l mem=100gb

#PBS -l walltime=12:00:00
#PBS -M Lawler.chloe@gmail.com
#PBS -m ae
#PBS -j oe


module add ruby/2.6.3
module add hmmer/3.3.1-mpi
module add parallel/20200722
module add kofamscan/1.3.0



for f in /srv/scratch/z5255670/kofam/*.faa; do
  $ ./exec_annotation --cpu=15 -E 0.01 --tmp-dir=${var} -p /srv/scratch/z5255670/kofam/ -k /srv/scratch/z5255670/kofam/ -f mapper -o result.txt query.fasta
done






done