#!/bin/bash

#PBS -l nodes=1:ppn=16
#PBS -l mem=122gb
#PBS -l walltime=480:00:00
#PBS -M lawler.chloe@gmail.com
#PBS -m ae
#PBS -j oe

source activate DRAM

cd /srv/scratch/burnslab/Chloe/DRAM

DRAM.py annotate -i '/srv/scratch/burnslab/Chloe/DRAM/*.fa' -o annotation
